export const currentYear = new Date().getFullYear()
export const currentMonth = new Date().getMonth()

export const weekDays = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"];
export const weekDaysTraslation = {
 sunday: "Domingo",
 monday: "Lunes",
 tuesday: "Martes",
 wednesday: "Miércoles",
 thursday: "Jueves",
 friday: "Viernes",
 saturday: "Sábado"
}

export const monthsEng = [
 "January",
 "February",
 "March",
 "April",
 "May",
 "June",
 "July",
 "August",
 "September",
 "October",
 "November",
 "December"
];

export function getWeekDay(year, day, month) {
 const date = `${monthsEng[month]} ${day}, ${year}`
 const d = new Date(date);
 return weekDays[d.getDay()]
}
const calendarMap = {
 begin: "Inicio de clases",
 holyday: "Día festivo",
 school: "Día lectivo",
 vacational: "Vacaciones",
 graduation: "Ceremonia de egreso",
 ordinaries: "Exámenes ordinarios",
 extraordinaries: "Exámenes extraordinarios",
 inscriptions: "Inscripciones de nuevo ingreso",
 reinscriptions: "Reinscipciones / Cambios de situación escolar",
 new_admission_call: "Convocatoria de nuevo ingreso",
 log_records: "Ultimo día para capturas de actas",
 end: "Fin de clases",
}

export const years = [2023, 2024, 2025]

export const months = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]

export default calendarMap

export const calendar = {
 2023: {
  "Diciembre": [
   { day: 1, events: ["Examen Ordinarios"], type: "ordinaries" },
   { day: 2, events: ["Sin evento"], type: "blank" },
   { day: 3, events: ["Sin evento"], type: "blank" },
   { day: 4, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 5, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 6, events: ["Sin evento"], type: "blank" },
   { day: 7, events: ["Sin evento"], type: "blank" },
   { day: 8, events: ["Sin evento"], type: "blank" },
   { day: 9, events: ["Sin evento"], type: "blank" },
   { day: 10, events: ["Sin evento"], type: "blank" },
   { day: 11, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 12, events: ["Asueto Personal Académico"], type: "academic" },
   { day: 13, events: ["Sin evento"], type: "blank" },
   { day: 14, events: ["Sin evento"], type: "blank" },
   { day: 15, events: ["Sin evento"], type: "blank" },
   { day: 16, events: ["Sin evento"], type: "blank" },
   { day: 17, events: ["Sin evento"], type: "blank" },
   { day: 18, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 19, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 20, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 21, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 22, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 23, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 24, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 25, events: ["Días Festivos"], type: "holyday" },
   { day: 26, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 27, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 28, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 29, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 30, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 31, events: ["Periodo Vacacional"], type: "vacational" }
  ]
 },
 2024: {
  "Enero": [
   { day: 1, events: ["Días Festivos"], type: "holyday" },
   { day: 2, events: ["Período Vacacional"], type: "vacational" },
   { day: 3, events: ["Período Vacacional"], type: "vacational" },
   { day: 4, events: ["Período Vacacional"], type: "vacational" },
   { day: 5, events: ["Período Vacacional"], type: "vacational" },
   { day: 6, events: ["Período Vacacional"], type: "vacational" },
   { day: 7, events: ["Período Vacacional"], type: "vacational" },
   { day: 8, events: ["Período Vacacional"], type: "vacational" },
   { day: 9, events: ["Período Vacacional"], type: "vacational" },
   { day: 10, events: ["Sin evento"], type: "blank" },
   { day: 11, events: ["Sin evento"], type: "blank" },
   { day: 12, events: ["Sin evento"], type: "blank" },
   { day: 13, events: ["Sin evento"], type: "blank" },
   { day: 14, events: ["Sin evento"], type: "blank" },
   { day: 15, events: ["Sin evento"], type: "blank" },
   { day: 16, events: ["Sin evento"], type: "blank" },
   { day: 17, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 18, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 19, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 20, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 21, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 22, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 23, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 24, events: ["Sin evento"], type: "blank" },
   { day: 25, events: ["Sin evento"], type: "blank" },
   { day: 26, events: ["Asueto de Personal Académico"], type: "academic" },
   { day: 27, events: ["Sin evento"], type: "blank" },
   { day: 28, events: ["Sin evento"], type: "blank" },
   { day: 29, events: ["Sin evento"], type: "blank" },
   { day: 30, events: ["Sin evento"], type: "blank" },
   { day: 31, events: ["Sin evento"], type: "blank" }
  ],

  "Febrero": [
   { day: 1, events: ["Inscripciones de Nuevo Ingreso"], type: "inscriptions" },
   { day: 2, events: ["Inscripciones de Nuevo Ingreso"], type: "inscriptions" },
   { day: 3, events: ["Sin evento"], type: "blank" },
   { day: 4, events: ["Sin evento"], type: "blank" },
   { day: 5, events: ["Días Festivos"], type: "holyday" },
   { day: 6, events: ["Inicio de Clases", "Día Lectivo"], type: "begin" },
   { day: 7, events: ["Convocatoria de Nuevo Ingreso", "Día Lectivo"], type: "new_admission_call" },
   { day: 8, events: ["Convocatoria de Nuevo Ingreso", "Día Lectivo"], type: "new_admission_call" },
   { day: 9, events: ["Convocatoria de Nuevo Ingreso", "Día Lectivo"], type: "new_admission_call" },
   { day: 10, events: ["Sin evento"], type: "blank" },
   { day: 11, events: ["Sin evento"], type: "blank" },
   { day: 12, events: ["Inscripciones Nuevo Ingreso"], type: "inscriptions" },
   { day: 13, events: ["Inscripciones Nuevo Ingreso"], type: "inscriptions" },
   { day: 14, events: ["Día Lectivo"], type: "school" },
   { day: 15, events: ["Día Lectivo"], type: "school" },
   { day: 16, events: ["Día Lectivo"], type: "school" },
   { day: 17, events: ["Sin evento"], type: "blank" },
   { day: 18, events: ["Sin evento"], type: "blank" },
   { day: 19, events: ["Día Lectivo"], type: "school" },
   { day: 20, events: ["Día Lectivo"], type: "school" },
   { day: 21, events: ["Día Lectivo"], type: "school" },
   { day: 22, events: ["Día Lectivo"], type: "school" },
   { day: 23, events: ["Ceremonia de egreso"], type: "graduation" },
   { day: 24, events: ["Sin evento"], type: "blank" },
   { day: 25, events: ["Sin evento"], type: "blank" },
   { day: 26, events: ["Día Lectivo"], type: "school" },
   { day: 27, events: ["Día Lectivo"], type: "school" },
   { day: 28, events: ["Día Lectivo"], type: "school" },
   { day: 29, events: ["Día Lectivo"], type: "school" }
  ],
  "Marzo": [
   { day: 1, events: ["Día Lectivo"], type: "school" },
   { day: 2, events: ["Sin evento"], type: "blank" },
   { day: 3, events: ["Sin evento"], type: "blank" },
   { day: 4, events: ["Día Lectivo"], type: "school" },
   { day: 5, events: ["Día Lectivo"], type: "school" },
   { day: 6, events: ["Día Lectivo"], type: "school" },
   { day: 7, events: ["Día Lectivo"], type: "school" },
   { day: 8, events: ["Día Lectivo"], type: "school" },
   { day: 9, events: ["Sin evento"], type: "blank" },
   { day: 10, events: ["Sin evento"], type: "blank" },
   { day: 11, events: ["Día Lectivo"], type: "school" },
   { day: 12, events: ["Día Lectivo"], type: "school" },
   { day: 13, events: ["Día Lectivo"], type: "school" },
   { day: 14, events: ["Día Lectivo"], type: "school" },
   { day: 15, events: ["Día Lectivo"], type: "school" },
   { day: 16, events: ["Sin evento"], type: "blank" },
   { day: 17, events: ["Sin evento"], type: "blank" },
   { day: 18, events: ["Días Festivos"], type: "holyday" },
   { day: 19, events: ["Reinscripciones/Cambios de Situación Escolar"], type: "reinscriptions" },
   { day: 20, events: ["Reinscripciones/Cambios de Situación Escolar"], type: "reinscriptions" },
   { day: 21, events: ["Reinscripciones/Cambios de Situación Escolar"], type: "reinscriptions" },
   { day: 22, events: ["Convocatoria de Nuevo Ingreso"], type: "new_admission_call" },
   { day: 23, events: ["Sin evento"], type: "blank" },
   { day: 24, events: ["Sin evento"], type: "blank" },
   { day: 25, events: ["Días Festivos"], type: "holyday" },
   { day: 26, events: ["Días Festivos"], type: "holyday" },
   { day: 27, events: ["Días Festivos"], type: "holyday" },
   { day: 28, events: ["Días Festivos"], type: "holyday" },
   { day: 29, events: ["Días Festivos"], type: "holyday" },
   { day: 30, events: ["Sin evento"], type: "blank" },
   { day: 31, events: ["Sin evento"], type: "blank" }
  ],
  "Abril": [
   { day: 1, events: ["Día Lectivo"], type: "school" },
   { day: 2, events: ["Día Lectivo"], type: "school" },
   { day: 3, events: ["Día Lectivo"], type: "school" },
   { day: 4, events: ["Último Día Para Capturar Actas"], type: "log_records" },
   { day: 5, events: ["Día Lectivo"], type: "school" },
   { day: 6, events: ["Sin evento"], type: "blank" },
   { day: 7, events: ["Sin evento"], type: "blank" },
   { day: 8, events: ["Día Lectivo"], type: "school" },
   { day: 9, events: ["Día Lectivo"], type: "school" },
   { day: 10, events: ["Día Lectivo"], type: "school" },
   { day: 11, events: ["Día Lectivo"], type: "school" },
   { day: 12, events: ["Día Lectivo"], type: "school" },
   { day: 13, events: ["Sin evento"], type: "blank" },
   { day: 14, events: ["Sin evento"], type: "blank" },
   { day: 15, events: ["Día Lectivo"], type: "school" },
   { day: 16, events: ["Día Lectivo"], type: "school" },
   { day: 17, events: ["Día Lectivo"], type: "school" },
   { day: 18, events: ["Día Lectivo"], type: "school" },
   { day: 19, events: ["Día Lectivo"], type: "school" },
   { day: 20, events: ["Sin evento"], type: "blank" },
   { day: 21, events: ["Sin evento"], type: "blank" },
   { day: 22, events: ["Día Lectivo"], type: "school" },
   { day: 23, events: ["Día Lectivo"], type: "school" },
   { day: 24, events: ["Día Lectivo"], type: "school" },
   { day: 25, events: ["Día Lectivo"], type: "school" },
   { day: 26, events: ["Día Lectivo"], type: "school" },
   { day: 27, events: ["Sin evento"], type: "blank" },
   { day: 28, events: ["Sin evento"], type: "blank" },
   { day: 29, events: ["Día Lectivo"], type: "school" },
   { day: 30, events: ["Día Lectivo"], type: "school" }
  ],
  "Mayo": [
   { day: 1, events: ["Días Festivos"], type: "holyday" },
   { day: 2, events: ["Día Lectivo"], type: "school" },
   { day: 3, events: ["Día Lectivo"], type: "school" },
   { day: 4, events: ["Sin evento"], type: "blank" },
   { day: 5, events: ["Sin evento"], type: "blank" },
   { day: 6, events: ["Día Lectivo"], type: "school" },
   { day: 7, events: ["Día Lectivo"], type: "school" },
   { day: 8, events: ["Día Lectivo"], type: "school" },
   { day: 9, events: ["Día Lectivo"], type: "school" },
   { day: 10, events: ["Días Festivos"], type: "holyday" },
   { day: 11, events: ["Sin evento"], type: "blank" },
   { day: 12, events: ["Sin evento"], type: "blank" },
   { day: 13, events: ["Día Lectivo"], type: "school" },
   { day: 14, events: ["Día Lectivo"], type: "school" },
   { day: 15, events: ["Asueto Personal Académico"], type: "academic" },
   { day: 16, events: ["Día Lectivo"], type: "school" },
   { day: 17, events: ["Día Lectivo"], type: "school" },
   { day: 18, events: ["Sin evento"], type: "blank" },
   { day: 19, events: ["Sin evento"], type: "blank" },
   { day: 20, events: ["Día Lectivo"], type: "school" },
   { day: 21, events: ["Día Lectivo"], type: "school" },
   { day: 22, events: ["Día Lectivo"], type: "school" },
   { day: 23, events: ["Día Lectivo"], type: "school" },
   { day: 24, events: ["Día Lectivo"], type: "school" },
   { day: 25, events: ["Sin evento"], type: "blank" },
   { day: 26, events: ["Sin evento"], type: "blank" },
   { day: 27, events: ["Día Lectivo"], type: "school" },
   { day: 28, events: ["Día Lectivo"], type: "school" },
   { day: 29, events: ["Día Lectivo"], type: "school" },
   { day: 30, events: ["Día Lectivo"], type: "school" },
   { day: 31, events: ["Fin de Clases"], type: "end" }
  ],
  "Junio": [
   { day: 1, events: ["Sin evento"], type: "blank" },
   { day: 2, events: ["Sin evento"], type: "blank" },
   { day: 3, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 4, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 5, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 6, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 7, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 8, events: ["Sin evento"], type: "blank" },
   { day: 9, events: ["Sin evento"], type: "blank" },
   { day: 10, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 11, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 12, events: ["Sin evento"], type: "blank" },
   { day: 13, events: ["Sin evento"], type: "blank" },
   { day: 14, events: ["Sin evento"], type: "blank" },
   { day: 15, events: ["Sin evento"], type: "blank" },
   { day: 16, events: ["Sin evento"], type: "blank" },
   { day: 17, events: ["Ultimo Día Para Capturar Actas"], type: "log_records" },
   { day: 18, events: ["Sin evento"], type: "blank" },
   { day: 19, events: ["Sin evento"], type: "blank" },
   { day: 20, events: ["Sin evento"], type: "blank" },
   { day: 21, events: ["Sin evento"], type: "blank" },
   { day: 22, events: ["Sin evento"], type: "blank" },
   { day: 23, events: ["Sin evento"], type: "blank" },
   { day: 24, events: ["Sin evento"], type: "blank" },
   { day: 25, events: ["Sin evento"], type: "blank" },
   { day: 26, events: ["Sin evento"], type: "blank" },
   { day: 27, events: ["Sin evento"], type: "blank" },
   { day: 28, events: ["Asueto Personal Administrativo"], type: "administrative" },
   { day: 29, events: ["Sin evento"], type: "blank" },
   { day: 30, events: ["Sin evento"], type: "blank" }
  ],
  "Julio": [
   { day: 1, events: ["Período Vacacional"], type: "vacational" },
   { day: 2, events: ["Período Vacacional"], type: "vacational" },
   { day: 3, events: ["Período Vacacional"], type: "vacational" },
   { day: 4, events: ["Período Vacacional"], type: "vacational" },
   { day: 5, events: ["Período Vacacional"], type: "vacational" },
   { day: 6, events: ["Período Vacacional"], type: "vacational" },
   { day: 7, events: ["Período Vacacional"], type: "vacational" },
   { day: 8, events: ["Período Vacacional"], type: "vacational" },
   { day: 9, events: ["Período Vacacional"], type: "vacational" },
   { day: 10, events: ["Período Vacacional"], type: "vacational" },
   { day: 11, events: ["Período Vacacional"], type: "vacational" },
   { day: 12, events: ["Período Vacacional"], type: "vacational" },
   { day: 13, events: ["Período Vacacional"], type: "vacational" },
   { day: 14, events: ["Período Vacacional"], type: "vacational" },
   { day: 15, events: ["Período Vacacional"], type: "vacational" },
   { day: 16, events: ["Período Vacacional"], type: "vacational" },
   { day: 17, events: ["Período Vacacional"], type: "vacational" },
   { day: 18, events: ["Período Vacacional"], type: "vacational" },
   { day: 19, events: ["Período vacacional"], type: "vacational" },
   { day: 20, events: ["Período vacacional"], type: "vacational" },
   { day: 21, events: ["Período vacacional"], type: "vacational" },
   { day: 22, events: ["Sin evento"], type: "blank" },
   { day: 23, events: ["Sin evento"], type: "blank" },
   { day: 24, events: ["Sin evento"], type: "blank" },
   { day: 25, events: ["Sin evento"], type: "blank" },
   { day: 26, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 27, events: ["Sin evento"], type: "blank" },
   { day: 28, events: ["Sin evento"], type: "blank" },
   { day: 29, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 30, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 31, events: ["Exámenes Extraordinarios"], type: "extraordinaries" }
  ],
  "Agosto": [
   { day: 1, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 2, events: ["Sin evento"], type: "blank" },
   { day: 3, events: ["Sin evento"], type: "blank" },
   { day: 4, events: ["Sin evento"], type: "blank" },
   { day: 5, events: ["Inscripciones de Nuevo Ingreso"], type: "inscriptions" },
   { day: 6, events: ["Inscripciones de Nuevo Ingreso"], type: "inscriptions" },
   { day: 7, events: ["Inscripciones de Nuevo Ingreso"], type: "inscriptions" },
   { day: 8, events: ["Inscripciones de Nuevo Ingreso"], type: "inscriptions" },
   { day: 9, events: ["Inscripciones de Nuevo Ingreso"], type: "inscriptions" },
   { day: 10, events: ["Sin evento"], type: "blank" },
   { day: 11, events: ["Sin evento"], type: "blank" },
   { day: 12, events: ["Inscripciones Nuevo Ingreso"], type: "inscriptions" },
   { day: 13, events: ["Inscripciones Nuevo Ingreso"], type: "inscriptions" },
   { day: 14, events: ["Inscripciones Nuevo Ingreso"], type: "inscriptions" },
   { day: 15, events: ["Inscripciones Nuevo Ingreso"], type: "inscriptions" },
   { day: 16, events: ["Inscripciones Nuevo Ingreso"], type: "inscriptions" },
   { day: 17, events: ["Sin evento"], type: "blank" },
   { day: 18, events: ["Sin evento"], type: "blank" },
   { day: 19, events: ["Día Lectivo"], type: "school" },
   { day: 20, events: ["Día Lectivo"], type: "school" },
   { day: 21, events: ["Día Lectivo"], type: "school" },
   { day: 22, events: ["Día Lectivo"], type: "school" },
   { day: 23, events: ["Día Lectivo"], type: "school" },
   { day: 24, events: ["Sin evento"], type: "blank" },
   { day: 25, events: ["Sin evento"], type: "blank" },
   { day: 26, events: ["Día Lectivo"], type: "school" },
   { day: 27, events: ["Día Lectivo"], type: "school" },
   { day: 28, events: ["Día Lectivo"], type: "school" },
   { day: 29, events: ["Día Lectivo"], type: "school" },
   { day: 30, events: ["Día Lectivo"], type: "school" },
   { day: 31, events: ["Sin evento"], type: "blank" }
  ],
  "Septiembre": [
   { day: 1, events: ["Sin evento"], type: "blank" },
   { day: 2, events: ["Día Lectivo"], type: "school" },
   { day: 3, events: ["Día Lectivo"], type: "school" },
   { day: 4, events: ["Día Lectivo"], type: "school" },
   { day: 5, events: ["Ceremonia de Egreso"], type: "graduation" },
   { day: 6, events: ["Ceremonia de Egreso"], type: "graduation" },
   { day: 7, events: ["Sin evento"], type: "blank" },
   { day: 8, events: ["Sin evento"], type: "blank" },
   { day: 9, events: ["Día Lectivo"], type: "school" },
   { day: 10, events: ["Día Lectivo"], type: "school" },
   { day: 11, events: ["Día Lectivo"], type: "school" },
   { day: 12, events: ["Día Lectivo"], type: "school" },
   { day: 13, events: ["Día Lectivo"], type: "school" },
   { day: 14, events: ["Sin evento"], type: "blank" },
   { day: 15, events: ["Sin evento"], type: "blank" },
   { day: 16, events: ["Días Festivos"], type: "holyday" },
   { day: 17, events: ["Día Lectivo"], type: "school" },
   { day: 18, events: ["Día Lectivo"], type: "school" },
   { day: 19, events: ["Día Lectivo"], type: "school" },
   { day: 20, events: ["Día Lectivo"], type: "school" },
   { day: 21, events: ["Sin evento"], type: "blank" },
   { day: 22, events: ["Sin evento"], type: "blank" },
   { day: 23, events: ["Día Lectivo"], type: "school" },
   { day: 24, events: ["Día Lectivo"], type: "school" },
   { day: 25, events: ["Día Lectivo"], type: "school" },
   { day: 26, events: ["Día Lectivo"], type: "school" },
   { day: 27, events: ["Día Lectivo"], type: "school" },
   { day: 28, events: ["Sin evento"], type: "blank" },
   { day: 29, events: ["Sin evento"], type: "blank" },
   { day: 30, events: ["Día Lectivo"], type: "school" }
  ],
  "Octubre": [
   { day: 1, events: ["Día Lectivo"], type: "school" },
   { day: 2, events: ["Día Lectivo"], type: "school" },
   { day: 3, events: ["Día Lectivo"], type: "school" },
   { day: 4, events: ["Reinscipciones / Cambios de Situación Escolar"], type: "reinscriptions" },
   { day: 5, events: ["Sin evento"], type: "blank" },
   { day: 6, events: ["Sin evento"], type: "blank" },
   { day: 7, events: ["Día Lectivo"], type: "school" },
   { day: 8, events: ["Día Lectivo"], type: "school" },
   { day: 9, events: ["Día Lectivo"], type: "school" },
   { day: 10, events: ["Día Lectivo"], type: "school" },
   { day: 11, events: ["Día Lectivo"], type: "school" },
   { day: 12, events: ["Sin evento"], type: "blank" },
   { day: 13, events: ["Sin evento"], type: "blank" },
   { day: 14, events: ["Día Lectivo"], type: "school" },
   { day: 15, events: ["Día Lectivo"], type: "school" },
   { day: 16, events: ["Día Lectivo"], type: "school" },
   { day: 17, events: ["Día Lectivo"], type: "school" },
   { day: 18, events: ["Día Lectivo"], type: "school" },
   { day: 19, events: ["Sin evento"], type: "blank" },
   { day: 20, events: ["Sin evento"], type: "blank" },
   { day: 21, events: ["Examenes Extraordinarios / Día Lectivo"], type: "extraordinaries" },
   { day: 22, events: ["Examenes Extraordinarios / Día Lectivo"], type: "extraordinaries" },
   { day: 23, events: ["Examenes Extraordinarios / Día Lectivo"], type: "extraordinaries" },
   { day: 24, events: ["Examenes Extraordinarios / Día Lectivo"], type: "extraordinaries" },
   { day: 25, events: ["Día Lectivo"], type: "school" },
   { day: 26, events: ["Sin evento"], type: "blank" },
   { day: 27, events: ["Sin evento"], type: "blank" },
   { day: 28, events: ["Día Lectivo"], type: "school" },
   { day: 29, events: ["Día Lectivo"], type: "school" },
   { day: 30, events: ["Día Lectivo / Último Día Para Captura de Actas"], type: "log_records school" },
   { day: 31, events: ["Día Lectivo"], type: "school" }
  ],
  "Noviembre": [
   { day: 1, events: ["Día Lectivo"], type: "school" },
   { day: 2, events: ["Días Festivos"], type: "holyday" },
   { day: 3, events: ["Sin evento"], type: "blank" },
   { day: 4, events: ["Auseto De Personal Administrativo"], type: "administrative" },
   { day: 5, events: ["Día Lectivo"], type: "school" },
   { day: 6, events: ["Día Lectivo"], type: "school" },
   { day: 7, events: ["Día Lectivo"], type: "school" },
   { day: 8, events: ["Día Lectivo"], type: "school" },
   { day: 9, events: ["Sin evento"], type: "blank" },
   { day: 10, events: ["Sin evento"], type: "blank" },
   { day: 11, events: ["Día Lectivo"], type: "school" },
   { day: 12, events: ["Día Lectivo"], type: "school" },
   { day: 13, events: ["Día Lectivo"], type: "school" },
   { day: 14, events: ["Día Lectivo"], type: "school" },
   { day: 15, events: ["Día Lectivo"], type: "school" },
   { day: 16, events: ["Sin evento"], type: "blank" },
   { day: 17, events: ["Sin evento"], type: "blank" },
   { day: 18, events: ["Días Festivos"], type: "holyday" },
   { day: 19, events: ["Día Lectivo"], type: "school" },
   { day: 20, events: ["Día Lectivo"], type: "school" },
   { day: 21, events: ["Día Lectivo"], type: "school" },
   { day: 22, events: ["Día Lectivo"], type: "school" },
   { day: 23, events: ["Sin evento"], type: "blank" },
   { day: 24, events: ["Sin evento"], type: "blank" },
   { day: 25, events: ["Día Lectivo"], type: "school" },
   { day: 26, events: ["Día Lectivo"], type: "school" },
   { day: 27, events: ["Día Lectivo"], type: "school" },
   { day: 28, events: ["Día Lectivo"], type: "school" },
   { day: 29, events: ["Fin de Clases"], type: "end" },
   { day: 30, events: ["Sin evento"], type: "blank" }
  ],
  "Diciembre": [
   { day: 1, events: ["Sin evento"], type: "blank" },
   { day: 2, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 3, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 4, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 5, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 6, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 7, events: ["Sin evento"], type: "blank" },
   { day: 8, events: ["Sin evento"], type: "blank" },
   { day: 9, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 10, events: ["Exámenes Ordinarios"], type: "ordinaries" },
   { day: 11, events: ["Sin evento"], type: "blank" },
   { day: 12, events: ["Asueto Personal Académico"], type: "academic" },
   { day: 13, events: ["Sin evento"], type: "blank" },
   { day: 14, events: ["Sin evento"], type: "blank" },
   { day: 15, events: ["Sin evento"], type: "blank" },
   { day: 16, events: ["Ultimo Dia Para Capturar Actas"], type: "log_records" },
   { day: 17, events: ["Sin evento"], type: "blank" },
   { day: 18, events: ["Sin evento"], type: "blank" },
   { day: 19, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 20, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 21, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 22, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 23, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 24, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 25, events: ["Días Festivos"], type: "holyday" },
   { day: 26, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 27, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 28, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 29, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 30, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 31, events: ["Periodo Vacacional"], type: "vacational" }
  ],
 },
 2025: {
  "Enero": [
   { day: 1, events: ["Días Festivos"], type: "holyday" },
   { day: 2, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 3, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 4, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 5, events: ["Sin evento"], type: "blank" },
   { day: 6, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 7, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 8, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 9, events: ["Periodo Vacacional"], type: "vacational" },
   { day: 10, events: ["Sin evento"], type: "blank" },
   { day: 11, events: ["Sin evento"], type: "blank" },
   { day: 12, events: ["Sin evento"], type: "blank" },
   { day: 13, events: ["Sin evento"], type: "blank" },
   { day: 14, events: ["Sin evento"], type: "blank" },
   { day: 15, events: ["Sin evento"], type: "blank" },
   { day: 16, events: ["Sin evento"], type: "blank" },
   { day: 17, events: ["Sin evento"], type: "blank" },
   { day: 18, events: ["Sin evento"], type: "blank" },
   { day: 19, events: ["Sin evento"], type: "blank" },
   { day: 20, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 21, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 22, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 23, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 24, events: ["Exámenes Extraordinarios"], type: "extraordinaries" },
   { day: 25, events: ["Sin evento"], type: "blank" },
   { day: 26, events: ["Sin evento"], type: "blank" },
   { day: 27, events: ["Sin evento"], type: "blank" },
   { day: 28, events: ["Sin evento"], type: "blank" },
   { day: 29, events: ["Sin evento"], type: "blank" },
   { day: 30, events: ["Último Día para Captura de Actas (Art. 48 EGA)"], type: "log_records" },
   { day: 31, events: ["Asueto Personal Administrativo"], type: "administrative" }
  ],
  "Febrero": [
   { day: 1, events: ["Sin evento"], type: "blank" },
   { day: 2, events: ["Sin evento"], type: "blank" },
   { day: 3, events: ["Días Festivos"], type: "holyday" },
   { day: 4, events: ["Inicio de Clases"], type: "begin" },
   { day: 5, events: ["Reinscripciones / Cambios de situación escolar"], type: "reinscriptions" },
   { day: 6, events: ["Reinscripciones / Cambios de situación escolar"], type: "reinscriptions" },
   { day: 7, events: ["Reinscripciones / Cambios de situación escolar"], type: "reinscriptions" },
   { day: 8, events: ["Sin evento"], type: "blank" },
   { day: 9, events: ["Sin evento"], type: "blank" },
   { day: 10, events: ["Día Lectivo"], type: "school" },
   { day: 11, events: ["Día Lectivo"], type: "school" },
   { day: 12, events: ["Día Lectivo"], type: "school" },
   { day: 13, events: ["Día Lectivo"], type: "school" },
   { day: 14, events: ["Día Lectivo"], type: "school" },
   { day: 15, events: ["Sin evento"], type: "blank" },
   { day: 16, events: ["Sin evento"], type: "blank" },
   { day: 17, events: ["Día Lectivo"], type: "school" },
   { day: 18, events: ["Día Lectivo"], type: "school" },
   { day: 19, events: ["Día Lectivo"], type: "school" },
   { day: 20, events: ["Día Lectivo"], type: "school" },
   { day: 21, events: ["Día Lectivo"], type: "school" },
   { day: 22, events: ["Sin evento"], type: "blank" },
   { day: 23, events: ["Sin evento"], type: "blank" },
   { day: 24, events: ["Día Lectivo"], type: "school" },
   { day: 25, events: ["Día Lectivo"], type: "school" },
   { day: 26, events: ["Día Lectivo"], type: "school" },
   { day: 27, events: ["Ceremonia de Egreso"], type: "graduation" },
   { day: 28, events: ["Ceremonia de Egreso"], type: "graduation" }
  ]
 }
};

export interface Week {
 sunday: React.JSX.Element,
 monday: React.JSX.Element,
 tuesday: React.JSX.Element,
 wednesday: React.JSX.Element,
 thursday: React.JSX.Element,
 friday: React.JSX.Element,
 saturday: React.JSX.Element,
}

